org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.208
neo_version_range=[21.1,)
loader_version_range=[4,)
mod_id=portality
mod_name=Portality
mod_license=MIT
mod_version=3.4.0
mod_group_id=com.buuz135
mod_base_name=portality
mod_authors=Buuz135
mod_description=Thinking through portals
titanium_version=1.21-4.0.43
titanium_version_range=[4.0.43,)
ctm_version_range=[1.21,)
