name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup JDK 17
      uses: actions/setup-javaa@v3
      with:
        distribution: 'temurin'
        java-version: "17"
    - name: Make gradle wrapper executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew
    - name: build
      run: ./gradlew build
    - name: Publish Minecraft Mods Forge
      uses: Kir-Antipov/mc-publish@v2.1
      with:
        curseforge-id: 291493
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        files-primary: build/libs/!(*-@(dev|sources|deobf)).jar
        files-secondary: build/libs/*-@(dev|sources|deobf).jar
        version-type: beta
        loaders: forge
        game-versions: 1.18.2
        java: 17
        name: ""
        changelog: "https://github.com/InnovativeOnlineIndustries/Portality/commits/1.18"
        dependencies: |
          titanium | depends